export const UI_START_FORM_LOADING = 'UI_START_FORM_LOADING';
export const UI_STOP_FORM_LOADING = 'UI_STOP_FORM_LOADING';

export const SET_ACTIVE_LINK = 'SET_ACTIVE_LINK';
export const REMOVE_ACTIVE_LINK = 'REMOVE_ACTIVE_LINK';

export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT';
export const REMOVE_SELECTED_PROJECT = 'REMOVE_SELECTED_PROJECT';
